import { z } from 'zod';

/**
 * SHARED CONSTANTS & HELPERS
 */
const dateSchema = z
  .string()
  .trim()
  .describe('Date in YYYY-MM or YYYY format.')
  .regex(
    /^\d{4}(-(0[1-9]|1[0-2]))?$/,
    'Please enter a valid date in YYYY-MM format (e.g., 2024-05)',
  );

const idSchema = z.string().trim().min(1, 'Missing ID');
const urlSchema = z.string().trim().nullable();

const optionalStringSchema = (message: string) =>
  z
    .string()
    .trim()
    .min(1, message)
    .or(z.literal(''))
    .transform((val) => val || null)
    .nullish();

/**
 * AI-FRIENDLY SCHEMAS (No transforms, no refinements)
 * These are used as the 'response_format' for OpenAI.
 */
const pureStringSchema = z.string().trim().nullable();
const pureUrlSchema = z.string().describe('A valid URL').or(z.literal('')).nullable();

const contactPureShape = {
  firstName: z.string().trim().min(1, 'First name is required'),
  lastName: z.string().trim().min(1, 'Last name is required'),
  headline: pureStringSchema,
  email: z.string().describe('A valid email address'),
  phone: pureStringSchema,
  location: pureStringSchema,
  websiteUrl: pureUrlSchema,
  linkedinUrl: pureUrlSchema,
  githubUrl: pureUrlSchema,
};

const skillPureShape = {
  id: idSchema,
  name: z.string().trim().min(1, 'Skill name is required'),
  category: pureStringSchema,
  level: z.enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED']).nullable(),
};

const bulletPureShape = {
  id: idSchema,
  text: z.string().trim().min(1, 'Bullet point text is required'),
};

const experiencePureShape = {
  id: idSchema,
  company: z.string().trim().min(1, 'Company is required'),
  title: z.string().trim().min(1, 'Job title is required'),
  location: pureStringSchema,
  startDate: dateSchema,
  endDate: dateSchema.nullable(),
  isCurrent: z.boolean().nullable(),
  tech: z.array(z.string().trim().min(1, 'Tech name is required')).nullable(),
  bullets: z.array(z.object(bulletPureShape).strict()),
};

const projectPureShape = {
  id: idSchema,
  name: z.string().trim().min(1, 'Project name is required'),
  role: pureStringSchema,
  startDate: dateSchema.nullable(),
  endDate: dateSchema.nullable(),
  isCurrent: z.boolean().nullable(),
  url: pureUrlSchema,
  repoUrl: pureUrlSchema,
  tech: z.array(z.string().trim().min(1, 'Tech name is required')).nullable(),
  bullets: z.array(z.object(bulletPureShape).strict()),
};

const educationPureShape = {
  id: idSchema,
  school: z.string().trim().min(1, 'School name is required'),
  degree: pureStringSchema,
  field: pureStringSchema,
  location: pureStringSchema,
  startDate: dateSchema.nullable(),
  endDate: dateSchema.nullable(),
  grade: z.string().trim().nullish(),
  notes: z.string().trim().nullish(),
  isCurrent: z.boolean().nullable(),
};

const certificationPureShape = {
  id: idSchema,
  name: z.string().trim().min(1, 'Certification name is required'),
  issuer: pureStringSchema,
  date: dateSchema.nullable(),
  url: urlSchema,
};

const languagePureShape = {
  id: idSchema,
  name: z.string().trim().min(1, 'Language is required'),
  level: pureStringSchema,
};

/**
 * This version of the schema is guaranteed to be JSON-Schema compatible.
 * Use this for OpenAI's zodResponseFormat.
 */
export const openAiResumeSchema = z.object({
  version: z.literal(1),
  contact: z.object(contactPureShape).strict(),
  summary: pureStringSchema,
  skills: z.array(z.object(skillPureShape).strict()),
  experiences: z.array(z.object(experiencePureShape).strict()),
  projects: z.array(z.object(projectPureShape).strict()),
  education: z.array(z.object(educationPureShape).strict()).nullable(),
  certifications: z.array(z.object(certificationPureShape).strict()).nullish(),
  languages: z.array(z.object(languagePureShape).strict()).nullish(),
});


/**
 * 1. BASE RESUME DATA SCHEMA
 * This is the structure stored in the database and generated by AI.
 */
export const baseResumeDataSchema = z.object({
  version: z.literal(1),
  contact: z
    .object({
      firstName: z.string().trim().min(1, 'First name is required'),
      lastName: z.string().trim().min(1, 'Last name is required'),
      headline: optionalStringSchema('Headline cannot be empty'),
      email: z.email('Invalid email address'),
      phone: optionalStringSchema('Phone number cannot be empty'),
      location: optionalStringSchema('Location cannot be empty'),
      websiteUrl: z
        .url({ message: 'Invalid website URL' })
        .regex(/^(https?:\/\/)?(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$/, {
          message: 'Must be a valid website URL',
        })
        .or(z.literal(''))
        .transform((val) => val || null)
        .nullish(),
      linkedinUrl: z
        .url({ message: 'Invalid LinkedIn URL' })
        .regex(/(?:https?:\/\/)?(?:www\.)?linkedin\.com/, {
          message: 'Must be a valid LinkedIn URL',
        })
        .or(z.literal(''))
        .transform((val) => val || null)
        .nullish(),
      githubUrl: z
        .url({ message: 'Invalid GitHub URL' })
        .regex(/(?:https?:\/\/)?(?:www\.)?github\.com/, {
          message: 'Must be a valid GitHub URL',
        })
        .or(z.literal(''))
        .transform((val) => val || null)
        .nullish(),
    })
    .strict(),
  summary: optionalStringSchema('Summary cannot be empty'),
  skills: z.array(
    z
      .object({
        id: idSchema,
        name: z.string().trim().min(1, 'Skill name is required'),
        category: optionalStringSchema('Category cannot be empty'),
        level: z.enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED']).nullish(),
      })
      .strict(),
  ),
  experiences: z.array(
    z
      .object({
        id: idSchema,
        company: z.string().trim().min(1, 'Company is required'),
        title: z.string().trim().min(1, 'Job title is required'),
        location: optionalStringSchema('Location cannot be empty'),
        startDate: dateSchema,
        endDate: dateSchema.nullish(),
        isCurrent: z.boolean().nullish(),
        tech: z
          .array(z.string().trim().min(1, 'Tech name is required'))
          .nullish(),
        bullets: z.array(
          z
            .object({
              id: idSchema,
              text: z.string().trim().min(1, 'Bullet point text is required'),
            })
            .strict(),
        ),
      })
      .strict()
      .superRefine((data, ctx) => {
        // If isCurrent, startDate is required
        if (data.isCurrent && !data.startDate) {
          ctx.addIssue({
            code: 'custom',
            message: 'Start date is required for current positions',
            path: ['startDate'],
          });
        }
        // If endDate exists, startDate is required
        if (data.endDate && !data.startDate) {
          ctx.addIssue({
            code: 'custom',
            message: 'Start date is required if end date is present',
            path: ['startDate'],
          });
        }
        // If startDate exists and not current, endDate is required
        if (data.startDate && !data.isCurrent && !data.endDate) {
          ctx.addIssue({
            code: 'custom',
            message: 'End date is required (or check "I currently work here")',
            path: ['endDate'],
          });
        }
        // Validate date range: startDate must be before or equal to endDate
        if (data.startDate && data.endDate) {
          if (data.startDate > data.endDate) {
            ctx.addIssue({
              code: 'custom',
              message: 'End date must be after start date',
              path: ['endDate'],
            });
          }
        }
      }),
  ),
  projects: z.array(
    z
      .object({
        id: idSchema,
        name: z.string().trim().min(1, 'Project name is required'),
        role: optionalStringSchema('Project role cannot be empty'),
        startDate: dateSchema.nullish(),
        endDate: dateSchema.nullish(),
        isCurrent: z.boolean().nullish(),
        url: z
          .url({ message: 'Invalid project URL' })
          .regex(
            /^(https?:\/\/)?(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$/,
            {
              message: 'Must be a valid URL',
            },
          )
          .or(z.literal(''))
          .transform((val) => val || null)
          .nullish(),
        repoUrl: z
          .url({ message: 'Invalid repository URL' })
          .regex(/(?:https?:\/\/)?(?:www\.)?github\.com/, {
            message: 'Must be a valid GitHub URL',
          })
          .or(z.literal(''))
          .transform((val) => val || null)
          .nullish(),
        tech: z
          .array(z.string().trim().min(1, 'Tech name is required'))
          .nullish(),
        bullets: z.array(
          z
            .object({
              id: idSchema,
              text: z.string().trim().min(1, 'Bullet point text is required'),
            })
            .strict(),
        ),
      })
      .strict()
      .superRefine((data, ctx) => {
        // If isCurrent, startDate is required
        if (data.isCurrent && !data.startDate) {
          ctx.addIssue({
            code: 'custom',
            message: 'Start date is required for active projects',
            path: ['startDate'],
          });
        }
        // If endDate exists, startDate is required
        if (data.endDate && !data.startDate) {
          ctx.addIssue({
            code: 'custom',
            message: 'Start date is required if end date is present',
            path: ['startDate'],
          });
        }
        // If startDate exists and not current, endDate is required
        if (data.startDate && !data.isCurrent && !data.endDate) {
          ctx.addIssue({
            code: 'custom',
            message:
              'End date is required (or check "I am currently working on this")',
            path: ['endDate'],
          });
        }
        // Validate date range: startDate must be before or equal to endDate
        if (data.startDate && data.endDate) {
          if (data.startDate > data.endDate) {
            ctx.addIssue({
              code: 'custom',
              message: 'End date must be after start date',
              path: ['endDate'],
            });
          }
        }
      }),
  ),
  education: z
    .array(
      z
        .object({
          id: idSchema,
          school: z
            .string({ error: 'Please enter your school or institution name' })
            .trim()
            .min(1, 'Please enter your school or institution name'),
          degree: optionalStringSchema('Degree cannot be empty'),
          field: optionalStringSchema('Field of study cannot be empty'),
          location: optionalStringSchema('Location cannot be empty'),
          startDate: dateSchema.nullish(),
          endDate: dateSchema.nullish(),
          grade: optionalStringSchema('Grade cannot be empty'),
          notes: z.string().trim().nullish(),
          isCurrent: z.boolean().nullish(),
        })
        .strict()
        .superRefine((data, ctx) => {
          // If isCurrent, startDate is required
          if (data.isCurrent && !data.startDate) {
            ctx.addIssue({
              code: 'custom',
              message: 'Start date is required if currently studying',
              path: ['startDate'],
            });
          }
          // If endDate exists, startDate is required
          if (data.endDate && !data.startDate) {
            ctx.addIssue({
              code: 'custom',
              message: 'Start date is required if graduation date is present',
              path: ['startDate'],
            });
          }
          // If startDate exists and not current, endDate is required
          if (data.startDate && !data.isCurrent && !data.endDate) {
            ctx.addIssue({
              code: 'custom',
              message:
                'Graduation date is required (or check "I am currently studying here")',
              path: ['endDate'],
            });
          }
          // Validate date range: startDate must be before or equal to endDate
          if (data.startDate && data.endDate) {
            if (data.startDate > data.endDate) {
              ctx.addIssue({
                code: 'custom',
                message: 'Graduation date must be after start date',
                path: ['endDate'],
              });
            }
          }
        }),
    )
    .nullish(),
  certifications: z
    .array(
      z
        .object({
          id: idSchema,
          name: z.string().trim().min(1, 'Certification name is required'),
          issuer: optionalStringSchema('Issuer cannot be empty'),
          date: dateSchema.nullish(),
          url: urlSchema,
        })
        .strict(),
    )
    .nullish(),
  languages: z
    .array(
      z
        .object({
          id: idSchema,
          name: z.string().trim().min(1, 'Language is required'),
          level: optionalStringSchema('Proficiency level cannot be empty'),
        })
        .strict(),
    )
    .nullish(),
});

export type BaseResumeData = z.infer<typeof baseResumeDataSchema>;

// Onboarding schema removed in favor of single source of truth (baseResumeDataSchema)

/**
 * 3. COMPATIBILITY EXPORTS
 */
// Exported type for the pure schema
export type OpenAiResumeData = z.infer<typeof openAiResumeSchema>;

