import { z } from 'zod';

/**
 * SHARED CONSTANTS & HELPERS
 */
const MonthRegex = /^(0[1-9]|1[0-2])$/;
const YearRegex = /^\d{4}$/;

const monthSchema = z.string().trim().regex(MonthRegex, 'Month must be 01-12');
const yearSchema = z.string().trim().regex(YearRegex, 'Year must be 4 digits');

const dateSchema = z
  .string()
  .trim()
  .describe('Date in YYYY-MM or YYYY format.')
  .regex(/^\d{4}(-(0[1-9]|1[0-2]))?$/, 'Expected YYYY or YYYY-MM');

const idSchema = z.string().trim().min(1);
const urlSchema = z.string().trim().nullable().optional();

/**
 * 1. BASE RESUME DATA SCHEMA
 * This is the structure stored in the database and generated by AI.
 */
export const baseResumeDataSchema = z
  .object({
    version: z.literal(1).optional().default(1),
    contact: z
      .object({
        firstName: z.string().trim().min(1),
        lastName: z.string().trim().min(1),
        headline: z.string().trim().min(1).nullable().optional(),
        email: z.string().trim().min(1),
        phone: z.string().trim().min(1).nullable().optional(),
        location: z.string().trim().min(1).nullable().optional(),
        websiteUrl: urlSchema,
        linkedinUrl: urlSchema,
        githubUrl: urlSchema,
      })
      .strict(),
    summary: z.string().trim().min(1).nullable().optional(),
    skills: z
      .array(
        z
          .object({
            id: idSchema,
            name: z.string().trim().min(1),
            category: z.string().trim().min(1).nullable().optional(),
            level: z
              .enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED'])
              .nullable()
              .optional(),
          })
          .strict(),
      )
      .default([]),
    experiences: z
      .array(
        z
          .object({
            id: idSchema,
            company: z.string().trim().min(1),
            title: z.string().trim().min(1),
            location: z.string().trim().min(1).nullable().optional(),
            startDate: dateSchema,
            endDate: dateSchema.nullable().optional(),
            isCurrent: z.boolean().nullable().optional(),
            tech: z.array(z.string().trim().min(1)).nullable().optional(),
            bullets: z.array(
              z
                .object({ id: idSchema, text: z.string().trim().min(1) })
                .strict(),
            ),
          })
          .strict(),
      )
      .default([]),
    projects: z
      .array(
        z
          .object({
            id: idSchema,
            name: z.string().trim().min(1),
            role: z.string().trim().min(1).nullable().optional(),
            startDate: dateSchema.nullable().optional(),
            endDate: dateSchema.nullable().optional(),
            isCurrent: z.boolean().nullable().optional(),
            url: urlSchema,
            repoUrl: urlSchema,
            tech: z.array(z.string().trim().min(1)).nullable().optional(),
            bullets: z.array(
              z
                .object({ id: idSchema, text: z.string().trim().min(1) })
                .strict(),
            ),
          })
          .strict(),
      )
      .default([]),
    education: z
      .array(
        z
          .object({
            id: idSchema,
            school: z.string().trim().min(1),
            degree: z.string().trim().min(1).nullable().optional(),
            field: z.string().trim().min(1).nullable().optional(),
            location: z.string().trim().min(1).nullable().optional(),
            startDate: dateSchema.nullable().optional(),
            endDate: dateSchema.nullable().optional(),
            grade: z.string().trim().min(1).nullable().optional(),
            notes: z.string().trim().min(1).nullable().optional(),
          })
          .strict(),
      )
      .nullable()
      .optional(),
    certifications: z
      .array(
        z
          .object({
            id: idSchema,
            name: z.string().trim().min(1),
            issuer: z.string().trim().min(1).nullable().optional(),
            date: dateSchema.nullable().optional(),
            url: urlSchema,
          })
          .strict(),
      )
      .nullable()
      .optional(),
    languages: z
      .array(
        z
          .object({
            id: idSchema,
            name: z.string().trim().min(1),
            level: z.string().trim().min(1).nullable().optional(),
          })
          .strict(),
      )
      .nullable()
      .optional(),
  })
  .strict();

export type BaseResumeData = z.infer<typeof baseResumeDataSchema>;

/**
 * 2. ONBOARDING FORM SCHEMA
 * This is what the frontend form uses. It maps to the Resume Schema.
 */
export const onboardingSchema = z.object({
  contact: z.object({
    firstName: z.string().trim().min(1, 'First name is required'),
    lastName: z.string().trim().min(1, 'Last name is required'),
    email: z.string().trim().email('Invalid email address'),
    phone: z.string().trim().optional().default(''),
    location: z.string().trim().min(1, 'Location is required'),
    githubUrl: z.string().trim().optional().default(''),
    linkedinUrl: z.string().trim().optional().default(''),
    websiteUrl: z.string().trim().optional().default(''),
  }),
  summary: z.string().trim().optional().default(''),
  experiences: z.array(z.object({
    id: z.string().min(1),
    title: z.string().trim().min(1, 'Title is required'),
    company: z.string().trim().min(1, 'Company is required'),
    startMonth: monthSchema,
    startYear: yearSchema,
    endMonth: z.string().trim().optional().default(''),
    endYear: z.string().trim().optional().default(''),
    isCurrent: z.boolean().default(false),
    description: z.string().trim().min(1, 'Description is required'),
  })).default([]),
  projects: z.array(z.object({
    id: z.string().min(1),
    name: z.string().trim().min(1, 'Name is required'),
    description: z.string().trim().min(10, 'Description too short'),
    tech: z.string().trim().min(1, 'Tech stack is required'),
    startMonth: z.string().trim().optional().default(''),
    startYear: z.string().trim().optional().default(''),
    endMonth: z.string().trim().optional().default(''),
    endYear: z.string().trim().optional().default(''),
    isCurrent: z.boolean().default(false),
    url: z.string().trim().optional().default(''),
    repoUrl: z.string().trim().optional().default(''),
  })).min(1, 'At least one project is required').default([]),
  skills: z.array(z.string().trim().min(1)).min(3, 'At least 3 skills required').default([]),
  education: z.object({
    school: z.string().trim().optional().default(''),
    degree: z.string().trim().optional().default(''),
    startMonth: z.string().trim().optional().default(''),
    startYear: z.string().trim().optional().default(''),
    endMonth: z.string().trim().optional().default(''),
    endYear: z.string().trim().optional().default(''),
    isSelfTaught: z.boolean().default(false),
  }),
});

export type OnboardingFormInput = z.input<typeof onboardingSchema>;
export type OnboardingFormValues = z.output<typeof onboardingSchema>;

/**
 * 3. COMPATIBILITY EXPORTS
 */
export const openAiResumeSchema = baseResumeDataSchema;
export type OpenAiResumeData = BaseResumeData;
