import { z } from 'zod';

/**
 * SHARED CONSTANTS & HELPERS
 */
const MonthRegex = /^(0[1-9]|1[0-2])$/;
const YearRegex = /^\d{4}$/;

const monthSchema = z.string().trim().regex(MonthRegex, 'Month must be 01-12');
const yearSchema = z.string().trim().regex(YearRegex, 'Year must be 4 digits');

const dateSchema = z
  .string()
  .trim()
  .describe('Date in YYYY-MM or YYYY format.')
  .regex(/^\d{4}(-(0[1-9]|1[0-2]))?$/, 'Expected YYYY or YYYY-MM');

const idSchema = z.string().trim().min(1);
const urlSchema = z.string().trim().nullable();

/**
 * 1. BASE RESUME DATA SCHEMA
 * This is the structure stored in the database and generated by AI.
 */
export const baseResumeDataSchema = z
  .object({
    version: z.literal(1),
    contact: z
      .object({
        firstName: z.string().trim().min(1),
        lastName: z.string().trim().min(1),
        headline: z.string().trim().min(1).nullable(),
        email: z.string().trim().min(1),
        phone: z.string().trim().min(1).nullable(),
        location: z.string().trim().min(1).nullable(),
        websiteUrl: urlSchema,
        linkedinUrl: urlSchema,
        githubUrl: urlSchema,
      })
      .strict(),
    summary: z.string().trim().min(1).nullable(),
    skills: z.array(
      z
        .object({
          id: idSchema,
          name: z.string().trim().min(1),
          category: z.string().trim().min(1).nullable(),
          level: z.enum(['BEGINNER', 'INTERMEDIATE', 'ADVANCED']).nullable(),
        })
        .strict(),
    ),
    experiences: z.array(
      z
        .object({
          id: idSchema,
          company: z.string().trim().min(1),
          title: z.string().trim().min(1),
          location: z.string().trim().min(1).nullable(),
          startDate: dateSchema,
          endDate: dateSchema.nullable(),
          isCurrent: z.boolean().nullable(),
          tech: z.array(z.string().trim().min(1)).nullable(),
          bullets: z.array(
            z.object({ id: idSchema, text: z.string().trim().min(1) }).strict(),
          ),
        })
        .strict()
        .superRefine((data, ctx) => {
          if (data.isCurrent && !data.startDate) {
            ctx.addIssue({
              code: 'custom',
              message: 'Start date is required for current positions',
              path: ['startDate'],
            });
          }
          if (data.endDate && !data.startDate) {
            ctx.addIssue({
              code: 'custom',
              message: 'Start date is required if end date is present',
              path: ['startDate'],
            });
          }
        }),
    ),
    projects: z.array(
      z
        .object({
          id: idSchema,
          name: z.string().trim().min(1),
          role: z.string().trim().min(1).nullable(),
          startDate: dateSchema.nullable(),
          endDate: dateSchema.nullable(),
          isCurrent: z.boolean().nullable(),
          url: urlSchema,
          repoUrl: urlSchema,
          tech: z.array(z.string().trim().min(1)).nullable(),
          bullets: z.array(
            z.object({ id: idSchema, text: z.string().trim().min(1) }).strict(),
          ),
        })
        .strict()
        .superRefine((data, ctx) => {
          if (data.isCurrent && !data.startDate) {
            ctx.addIssue({
              code: z.ZodIssueCode.custom,
              message: 'Start date is required for active projects',
              path: ['startDate'],
            });
          }
          if (data.endDate && !data.startDate) {
            ctx.addIssue({
              code: z.ZodIssueCode.custom,
              message: 'Start date is required if end date is present',
              path: ['startDate'],
            });
          }
        }),
    ),
    education: z
      .array(
        z
          .object({
            id: idSchema,
            school: z.string().trim().min(1),
            degree: z.string().trim().min(1).nullable(),
            field: z.string().trim().min(1).nullable(),
            location: z.string().trim().min(1).nullable(),
            startDate: dateSchema.nullable(),
            endDate: dateSchema.nullable(),
            grade: z.string().trim().min(1).nullable(),
            notes: z.string().trim().min(1).nullable(),
            isSelfTaught: z.boolean().nullable(),
          })
          .strict(),
      )
      .nullable(),
    certifications: z
      .array(
        z
          .object({
            id: idSchema,
            name: z.string().trim().min(1),
            issuer: z.string().trim().min(1).nullable(),
            date: dateSchema.nullable(),
            url: urlSchema,
          })
          .strict(),
      )
      .nullable(),
    languages: z
      .array(
        z
          .object({
            id: idSchema,
            name: z.string().trim().min(1),
            level: z.string().trim().min(1).nullable(),
          })
          .strict(),
      )
      .nullable(),
  })
  .strict();

export type BaseResumeData = z.infer<typeof baseResumeDataSchema>;

/**
 * 2. ONBOARDING FORM SCHEMA
 * This is what the frontend form uses. It maps to the Resume Schema.
 */
export const onboardingSchema = z.object({
  contact: z.object({
    firstName: z.string().trim().min(1, 'First name is required').max(50),
    lastName: z.string().trim().min(1, 'Last name is required').max(50),
    email: z.string().trim().email('Invalid email address').max(100),
    phone: z.string().trim().max(30).optional().default(''),
    location: z.string().trim().min(2, 'Location is required').max(100),
    githubUrl: z.string().trim().max(200).optional().default(''),
    linkedinUrl: z.string().trim().max(200).optional().default(''),
    websiteUrl: z.string().trim().max(200).optional().default(''),
  }),
  summary: z
    .string()
    .trim()
    .max(1000, 'Summary is too long')
    .optional()
    .default(''),
  experiences: z
    .array(
      z
        .object({
          id: z.string().min(1),
          title: z.string().trim().min(2, 'Title is required').max(100),
          company: z.string().trim().min(2, 'Company is required').max(100),
          startMonth: monthSchema,
          startYear: yearSchema,
          endMonth: z.string().trim().optional().default(''),
          endYear: z.string().trim().optional().default(''),
          isCurrent: z.boolean().default(false),
          description: z
            .string()
            .trim()
            .min(50, 'Provide more detail (min 50 chars) for better AI results')
            .max(2000),
        })
        .superRefine((data, ctx) => {
          if (!data.isCurrent) {
            if (!data.endMonth || !MonthRegex.test(data.endMonth)) {
              ctx.addIssue({
                code: 'custom',
                message: 'End month is required',
                path: ['endMonth'],
              });
            }
            if (!data.endYear || !YearRegex.test(data.endYear)) {
              ctx.addIssue({
                code: 'custom',
                message: 'End year is required',
                path: ['endYear'],
              });
            }
          }
        }),
    )
    .default([]),
  projects: z
    .array(
      z
        .object({
          id: z.string().min(1),
          name: z.string().trim().min(2, 'Name is required').max(100),
          description: z
            .string()
            .trim()
            .min(30, 'Provide more detail (min 30 chars) for better AI results')
            .max(2000),
          tech: z.string().trim().min(1, 'Tech stack is required').max(500),
          startMonth: monthSchema,
          startYear: yearSchema,
          endMonth: z.string().trim().optional().default(''),
          endYear: z.string().trim().optional().default(''),
          isCurrent: z.boolean().default(false),
          url: z.string().trim().max(200).optional().default(''),
          repoUrl: z.string().trim().max(200).optional().default(''),
        })
        .superRefine((data, ctx) => {
          if (!data.isCurrent) {
            if (!data.endMonth || !MonthRegex.test(data.endMonth)) {
              ctx.addIssue({
                code: 'custom',
                message: 'End month is required',
                path: ['endMonth'],
              });
            }
            if (!data.endYear || !YearRegex.test(data.endYear)) {
              ctx.addIssue({
                code: 'custom',
                message: 'End year is required',
                path: ['endYear'],
              });
            }
          }
        }),
    )
    .min(1, 'At least one project is required')
    .default([]),
  skills: z
    .array(z.string().trim().min(1))
    .min(5, 'At least 5 skills required for an optimal resume')
    .default([]),
  education: z
    .object({
      school: z.string().trim().max(100).optional().default(''),
      degree: z.string().trim().max(100).optional().default(''),
      startMonth: z.string().trim().optional().default(''),
      startYear: z.string().trim().optional().default(''),
      endMonth: z.string().trim().optional().default(''),
      endYear: z.string().trim().optional().default(''),
      isSelfTaught: z.boolean().default(false),
    })
    .superRefine((data, ctx) => {
      if (!data.isSelfTaught) {
        if (!data.school || data.school.length < 1) {
          ctx.addIssue({
            code: 'custom',
            message: 'School is required',
            path: ['school'],
          });
        }
        if (!data.startMonth || !MonthRegex.test(data.startMonth)) {
          ctx.addIssue({
            code: 'custom',
            message: 'Start month is required',
            path: ['startMonth'],
          });
        }
        if (!data.startYear || !YearRegex.test(data.startYear)) {
          ctx.addIssue({
            code: 'custom',
            message: 'Start year is required',
            path: ['startYear'],
          });
        }
        if (!data.endMonth || !MonthRegex.test(data.endMonth)) {
          ctx.addIssue({
            code: 'custom',
            message: 'Graduation month is required',
            path: ['endMonth'],
          });
        }
        if (!data.endYear || !YearRegex.test(data.endYear)) {
          ctx.addIssue({
            code: 'custom',
            message: 'Graduation year is required',
            path: ['endYear'],
          });
        }
      }
    }),
});

export type OnboardingFormInput = z.input<typeof onboardingSchema>;
export type OnboardingFormValues = z.output<typeof onboardingSchema>;

/**
 * 3. COMPATIBILITY EXPORTS
 */
export const openAiResumeSchema = baseResumeDataSchema;
export type OpenAiResumeData = BaseResumeData;
