import type { DetectedAreaRuleContext } from '../../project-structure-detected-areas.types';
import { applyDeclarativeAreaDetector } from '../declarative-area-rule-engine';
import { resolveUnitRootOwner } from '../owner-adapters';

/**
 * Path-only Flutter signal contract for owner-scoped scoring, grounded in a
 * GitHub-tree survey of ten real repositories (flutter/samples, fluffychat,
 * cake_wallet, invoiceninja/admin-portal, immich, ente, AppFlowy,
 * stack_wallet, plus dart-lang/http and dart-lang/args as plain-Dart
 * negative controls):
 * - `flutter-metadata` (`.metadata` at the unit root): generated by the
 *   `flutter create` CLI itself, never by `dart create`. Present on 7 of 8
 *   sampled real Flutter units; the one miss (immich's internal
 *   `mobile/packages/ui/`) is a plain-Dart-flavored helper package, not an
 *   app or plugin, which agrees with the signal rather than undermining it.
 *   Zero false positives against both controls: in dart-lang/http's mixed
 *   monorepo it appears on exactly its 4 real Flutter units (`cronet_http`,
 *   `cupertino_http`, its `ios_test`, `flutter_http_example`) and never on
 *   its 11 plain-Dart libraries.
 * - `flutter-pubspec-manifest` (`pubspec.yaml`): the expected anchor, but
 *   it's Dart's manifest, not Flutter's -- every plain-Dart package in both
 *   control repos has one too, and path-only matching cannot read the
 *   `flutter:` key inside it. Never trusted alone (see the gate below), same
 *   reasoning Expo's own gate applies to `app.config.ts` against Nuxt 3.
 *   Confirmed false-negative case: stack_wallet's own `.gitignore` excludes
 *   `pubspec.yaml` outright -- it's templated at build time from
 *   `scripts/app_config/templates/pubspec.template.yaml` -- so a real, large,
 *   actively-maintained Flutter app can commit no `pubspec.yaml` at all.
 * - `flutter-ios-platform-dir` (`ios/flutter/{debug,release}.xcconfig` or
 *   `appframeworkinfo.plist`): a directory literally named `Flutter` inside
 *   `ios/` -- no other iOS toolchain creates one. 30 of 30 sampled file hits
 *   landed inside exactly 10 such directories, one per iOS-enabled unit --
 *   100% co-occurrence regardless of which of the three files a team
 *   happens to commit.
 * - `flutter-macos-platform-dir` (`macos/flutter/flutter-{debug,release}
 *   .xcconfig` or `generatedpluginregistrant.swift`): the same shape one
 *   platform over. Rarer since desktop targets are opt-in, zero false
 *   positives when present.
 * - `flutter-desktop-cmake` (`{linux,windows}/flutter/cmakelists.txt`):
 *   generic filename, distinctive path -- nested one level under a directory
 *   literally named `flutter/`. More reliable than the neighboring
 *   `generated_plugin_registrant.cc`, which was missing (gitignored) in
 *   roughly 30% of the same directories in the sample.
 * - `flutter-entrypoint` (`lib/main.dart`): app-shaped convention, absent by
 *   design on plugin/package units that export a library instead (most of
 *   ente's ~40 internal packages have no `main.dart`).
 * - `flutter-android-splash`
 *   (`android/app/src/main/res/drawable(-*)?/launch_background.xml`): the
 *   exact filename `flutter create` scaffolds for the launch splash, 1:1
 *   with sampled Android units. Not anchor-grade -- a hand-built native
 *   Android app could coincidentally reuse the same filename -- but no other
 *   framework's default template uses it, so real-world collision risk is
 *   low.
 * - `flutter-integration-test-dir` (`integration_test/`): the literal name of
 *   Flutter's own official test package, not a generic "integration tests"
 *   folder. Present in 6 of 8 sampled repos; re-checked directly against
 *   both controls for this pass -- zero hits in dart-lang/args, and every
 *   hit in dart-lang/http sits inside one of its 4 Flutter units, never
 *   inside a plain-Dart library.
 *
 * `.fvmrc`/`.fvm/` (Flutter Version Management) was researched and left out:
 * real, zero-false-positive tooling, but only 1 of 8 sampled repos used it
 * and it does not indicate a different related technology the way React
 * Native's `expo-modules-coexistence` does -- cheap to add later, not
 * worth the surface now.
 */
const FLUTTER_MOBILE_SIGNAL_SCORES = {
  'flutter-metadata': 4,
  'flutter-pubspec-manifest': 4,
  'flutter-ios-platform-dir': 3,
  'flutter-macos-platform-dir': 2,
  'flutter-desktop-cmake': 2,
  'flutter-entrypoint': 2,
  'flutter-android-splash': 1,
  'flutter-integration-test-dir': 1,
} as const;

type FlutterMobileSignal = keyof typeof FLUTTER_MOBILE_SIGNAL_SCORES;

/**
 * Adds a `Mobile app` candidate for Flutter evidence.
 *
 * Inputs: `context.candidates` (shared `(area name, owner path)` map, mutated
 * in place) and `context.index` (repository path/name/extension lookup).
 * Output: none.
 * Side effects: adds or accumulates a `Mobile app` candidate with primary
 * technology `Flutter` (related: `Dart`) for every owner whose counted
 * signals clear the gate.
 *
 * Owner: `resolveUnitRootOwner`, unmodified, with
 * `extraRootDirectories: ['example']` for the same library-demo-app
 * convention Expo and React Native already needed (confirmed in AppFlowy's
 * internal packages, e.g. `packages/appflowy_ui/example/pubspec.yaml`).
 * `flutter-metadata` and `flutter-pubspec-manifest` are anchors sitting at
 * the plain unit root, so the adapter's default anchor-dirname behavior
 * applies unchanged -- no new anchor shape was needed. The non-anchor
 * `flutter-ios-platform-dir` and `flutter-android-splash` signals both
 * contain an `android`/`ios` path segment, so they already resolve correctly
 * through the adapter's existing React-Native-authored fallback (everything
 * before that segment) even when no anchor is present nearby. The remaining
 * non-anchor signals (`flutter-macos-platform-dir`, `flutter-desktop-cmake`,
 * `flutter-entrypoint`, `flutter-integration-test-dir`) have no equivalent
 * fallback and depend on an anchor already having claimed the enclosing
 * owner, or fall through to the generic `ownerPathForApplicationArea`
 * resolver -- same limitation already accepted for React Native's own
 * non-anchor supportive signals. No owner-adapter changes were made in this
 * pass.
 *
 * Gate: `flutter-pubspec-manifest` can never clear the gate alone (it's
 * Dart's manifest, not Flutter's -- see the false-positive risk above), and
 * neither can any lone platform-directory signal by itself carry an owner
 * with no other Flutter evidence. Three branches, mirroring how React
 * Native's own gate covers both a with-config and a without-config case:
 * - Branch A: `flutter-metadata` + `flutter-pubspec-manifest` -- the clean,
 *   complete unit; 6 of 8 sampled repos clear this alone.
 * - Branch B: `flutter-metadata` + one platform-directory signal (iOS,
 *   macOS, or desktop) -- covers stack_wallet's gitignored-manifest case,
 *   where `.metadata` survives but `pubspec.yaml` does not.
 * - Branch C: `flutter-pubspec-manifest` + one platform-directory signal --
 *   the symmetric hedge for a team that scrubs `.metadata` but keeps the
 *   manifest. Not observed in this sample; structurally plausible only, the
 *   same kind of unobserved-but-reasoned branch React Native's own gate
 *   carries for its without-config case.
 *
 * Flutter shares no file-level signals with Expo or React Native (different
 * manifest, different native bootstrap), so there is no cross-detector
 * overlap in that direction. It does collide with the native Android/iOS
 * detectors' shells (see Limitations); those detectors resolve a bundled
 * shell's owner to the Flutter root through `resolveNearestMarkerOwner`
 * (`pubspec.yaml`/`.metadata` marker), and `reconcileCandidates` drops the
 * native candidate.
 *
 * Limitations:
 * - Path-only, so `pubspec.yaml`'s `flutter:` key cannot be read to confirm
 *   a Flutter (vs. plain Dart) dependency directly.
 * - `android/app/src/main/{kotlin,java}/**\/MainActivity.*` plus
 *   `AndroidManifest.xml` is structurally identical to a fully native
 *   Android app's host project -- no path-only Android-side signal exists to
 *   tell them apart, mirrored by the deliberate absence of an Android-shell
 *   signal here (unlike React Native, which does score one). Handled on the
 *   native Android/iOS side by owner redirection and `reconcileCandidates`,
 *   per the note above.
 * - Sample size (8 real Flutter repos + 2 controls) is smaller than Expo's
 *   ~90-repo or React Native's ~13k-hit code-search passes -- a first
 *   research pass, not a finished grounding.
 * - Owner resolution across dense monorepos (ente alone has 47
 *   `pubspec.yaml` roots) is out of scope for this pass; this detector only
 *   characterizes and scores per-unit signals.
 */
export function addFlutterMobileAreas({
  candidates,
  index,
}: DetectedAreaRuleContext): void {
  applyDeclarativeAreaDetector<FlutterMobileSignal>({
    candidates,
    index,
    detectedArea: 'Mobile app',
    primaryTech: 'Flutter',
    relatedTechs: ['Dart'],
    signalScores: FLUTTER_MOBILE_SIGNAL_SCORES,
    entrySchemas: [
      {
        signalType: 'flutter-metadata',
        regex: /^\.metadata$/,
        indexMethod: 'findFilesByNameMatching',
        isAnchorSignal: true,
      },
      {
        signalType: 'flutter-pubspec-manifest',
        regex: /^pubspec\.yaml$/,
        indexMethod: 'findFilesByNameMatching',
        isAnchorSignal: true,
      },
      {
        signalType: 'flutter-ios-platform-dir',
        regex:
          /(^|\/)ios\/flutter\/(debug\.xcconfig|release\.xcconfig|appframeworkinfo\.plist)$/,
        indexMethod: 'findEntriesByPathMatching',
      },
      {
        signalType: 'flutter-macos-platform-dir',
        regex:
          /(^|\/)macos\/flutter\/(flutter-debug\.xcconfig|flutter-release\.xcconfig|generatedpluginregistrant\.swift)$/,
        indexMethod: 'findEntriesByPathMatching',
      },
      {
        signalType: 'flutter-desktop-cmake',
        regex: /(^|\/)(linux|windows)\/flutter\/cmakelists\.txt$/,
        indexMethod: 'findEntriesByPathMatching',
      },
      {
        signalType: 'flutter-entrypoint',
        regex: /(^|\/)lib\/main\.dart$/,
        indexMethod: 'findEntriesByPathMatching',
      },
      {
        signalType: 'flutter-android-splash',
        regex:
          /(^|\/)android\/app\/src\/main\/res\/drawable(-[a-z0-9-]+)?\/launch_background\.xml$/,
        indexMethod: 'findEntriesByPathMatching',
      },
      {
        signalType: 'flutter-integration-test-dir',
        regex: /(^|\/)integration_test$/,
        indexMethod: 'findDirectoriesByPathMatching',
      },
    ],
    gateBlocker: {
      where: {
        countedSignals: {
          or: [
            // Branch A: the clean, complete unit.
            {
              hasAllOf: ['flutter-metadata', 'flutter-pubspec-manifest'],
            },
            // Branch B: .metadata survives a gitignored manifest.
            {
              and: [
                { has: 'flutter-metadata' },
                {
                  hasOneOf: [
                    'flutter-ios-platform-dir',
                    'flutter-macos-platform-dir',
                    'flutter-desktop-cmake',
                  ],
                },
              ],
            },
            // Branch C: symmetric hedge -- manifest survives a scrubbed .metadata.
            {
              and: [
                { has: 'flutter-pubspec-manifest' },
                {
                  hasOneOf: [
                    'flutter-ios-platform-dir',
                    'flutter-macos-platform-dir',
                    'flutter-desktop-cmake',
                  ],
                },
              ],
            },
          ],
        },
      },
    },
    ownerAdapter: (args) =>
      resolveUnitRootOwner({ ...args, extraRootDirectories: ['example'] }),
  });
}
