export enum ErrorCode {
  // Auth errors
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  FORBIDDEN = 'FORBIDDEN',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // General errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',

  // AI-specific errors
  AI_GENERATION_ERROR = 'AI_GENERATION_ERROR',
  AI_PARSE_ERROR = 'AI_PARSE_ERROR',
  AI_TIMEOUT_ERROR = 'AI_TIMEOUT_ERROR',
  INSUFFICIENT_DATA = 'INSUFFICIENT_DATA',

  // Infrastructure errors
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  NETWORK_ERROR = 'NETWORK_ERROR',

  // GitHub OAuth errors
  GITHUB_TOKEN_EXCHANGE_FAILED = 'GITHUB_TOKEN_EXCHANGE_FAILED',
  GITHUB_USER_FETCH_FAILED = 'GITHUB_USER_FETCH_FAILED',
  GITHUB_OAUTH_ERROR = 'GITHUB_OAUTH_ERROR',
  GITHUB_REPOS_FETCH_FAILED = 'GITHUB_REPOS_FETCH_FAILED',
  GITHUB_CONNECTION_FETCH_FAILED = 'GITHUB_CONNECTION_FETCH_FAILED',
}
